# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "91d691a8052271cd7cc8f3bd814bb447"
name = "observa-development"
application_url = "https://observa--development.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = ["https://observa--development.gadget.app/api/connections/auth/shopify/callback"]

[webhooks]
api_version = "2025-10"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact" ,"shop/redact"]
uri = "https://observa--development.gadget.app/api/webhooks/shopify"
