# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml
client_id = "826d5f9117980f05fccd0d5b3e50a44a"
name = "observa-development"
application_url = "https://observa--development.gadget.app/api/shopify/install-or-render"
embedded = true
handle = "observa-development-2"

[auth]
redirect_urls = [ "https://observa--development.gadget.app/api/connections/auth/shopify/callback" ]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://webhooks.gadget-services.net/shopify/v1?domain=observa--development.gadget.app"
topics = [ "shop/update", "app/uninstalled" ]

# Trigger key: handleOrderCreate
[[webhooks.subscriptions]]
uri = "https://webhooks.gadget-services.net/shopify/v1/handleOrderCreate?domain=observa--development.gadget.app"
topics = [ "orders/create" ]

# Trigger key: handleOrderUpdated
[[webhooks.subscriptions]]
uri = "https://webhooks.gadget-services.net/shopify/v1/handleOrderUpdated?domain=observa--development.gadget.app"
topics = [ "orders/updated" ]

# Trigger key: handleCheckoutCreate
[[webhooks.subscriptions]]
uri = "https://webhooks.gadget-services.net/shopify/v1/handleCheckoutCreate?domain=observa--development.gadget.app"
topics = [ "checkouts/create" ]

# Trigger key: handleInventoryUpdate
[[webhooks.subscriptions]]
uri = "https://webhooks.gadget-services.net/shopify/v1/handleInventoryUpdate?domain=observa--development.gadget.app"
topics = [ "inventory_levels/update" ]

[access_scopes]
scopes = "read_checkouts, read_customers, read_orders, read_analytics, read_products, read_fulfillments, read_merchant_managed_fulfillment_orders, read_reports, read_inventory"
