# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "c99a307627a5f0f964a5b2d43209f454"
name = "wably-development"
application_url = "https://wably--development.gadget.app/api/shopify/install-or-render"
embedded = true

handle = "wably-development"
[auth]
redirect_urls = [ "https://wably--development.gadget.app/api/connections/auth/shopify/callback" ]

[access_scopes]
scopes = "read_script_tags, write_script_tags, read_themes, read_customers, read_online_store_pages"

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
uri = "https://webhooks.gadget-services.net/shopify/v1?domain=wably--development.gadget.app"
topics = [ "shop/update", "app/uninstalled" ]
